---
name: ItemFrame-Protector
author: TheNote
version: 2.0.0
api: 
- 3.0.0
main: TheNote\ItemFrameProtector\Main
commands:
  itemframes:
    description: "Change ItemFrameProtector settings"
    permission: itemframes.tools
  banitemframes:
    description: "Change ItemFrameProtector settings"
    permission: itemframes.tools
permissions:
  itemframes.tools:
    default: op
    description: "Allow to change ItemFrameProtector settings"
...
