# ------------------------------------------------------
# ItemFrameProtector by TheNote - Config
# ------------------------------------------------------

# In welcherer Welt sollen Item-Frames Geschützt werden?
ProtectedWorlds:
- "world"